[package]
name = "binary_extract_deno"
version = "0.0.0"
edition = "2021"

[dependencies]
deno_bindgen = "0.5.1"
serde = { version = "1.0.137", features = ["derive"] }
binary_extract = { path = "../" }

[lib]
name = "deno_bindgen_test"
crate-type = ["cdylib"]
