[package]
name = "binary_extract"
version = "0.0.0"
edition = "2021"


[dependencies]
anyhow = "1.0.57"
tar = "0.4.38"
flate2 = "1.0.24"
zip = "0.6.2"

[dev-dependencies]
testing = "0.20.1"
insta = "1.14.1"
