name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  # Lint the project
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install and audit
        uses: ./.github/actions/pnpm

      - name: check TS / JS files
        run: pnpm lint:es

      - name: check formatting
        run: pnpm lint:prettier

      - name: check repo and versions
        run: pnpm lint:repo

      - name: check build
        run: pnpm lint:build

  # Unit test and update coverage report
  unit_test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install and audit
        uses: ./.github/actions/pnpm

      - name: run unit tests
        run: pnpm test

  # Build the project and run tests on built files.
  build_test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
      fail-fast: false

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install and audit
        uses: ./.github/actions/pnpm
        with:
          node-version: ${{ matrix.node-version }}

      - name: build project
        run: pnpm build

      - name: run unit tests
        run: pnpm test

  changeset:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    if: ${{ false == contains(github.ref, 'changeset') && github.repository == 'kickjump/kickjump' }}
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install and audit
        uses: ./.github/actions/pnpm

      - name: check versions are valid
        if: github.event.pull_request
        run: |
          pnpm version:pr
          pnpm version:ci
