## Listens to the CI workflow and runs the publish command to main when applicable.

name: publish

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types: [completed]

jobs:
  # Publish the project to npm
  npm:
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install and audit
        uses: ./.github/actions/pnpm

      - name: build project
        run: pnpm build

      - name: add token
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: create versions
        uses: changesets/action@v1
        if: github.event.workflow_run.head_branch == 'main'
        with:
          version: pnpm version:ci
          publish: pnpm release
          commit: 'chore(changeset): version update'
          title: 'chore(changeset): version update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
